require 'benchmark'
require_relative '../compiler'
Dir.chdir(File.dirname(File.dirname(__FILE__)))


task :default => [:include]

Compiler.list.each do |cc|
  task :include => ["include/#{cc.id}"]
  rule "include/#{cc.id}" do
    cc.compile_file('include/mpl11.cpp') # rehearse
    mpl11 = cc.compile_file('include/mpl11.cpp', &Benchmark.method(:realtime))

    cc.compile_file('include/mpl.cpp') # rehearse
    mpl = cc.compile_file('include/mpl.cpp', &Benchmark.method(:realtime))

    puts <<-EOS
  Including the whole library with #{cc}:
  mpl:       #{mpl} s
  mpl11:     #{mpl11} s
  mpl/mpl11: #{mpl/mpl11}
  EOS
  end
end
