require_relative '../compiler'
require_relative '../utility'
Dir.chdir(File.dirname(File.dirname(__FILE__)))


task :default => ['logical_or']

implementations = Dir['logical_or/*.rb'].map { |file|
  File.remove_ext(File.basename(file))
}

Compiler.list.map(&:id).each do |cc|
  datasets = -> (re) {
    implementations.grep(re).map { |impl| "dataset/logical_or/#{cc}/#{impl}" }
  }

  task :logical_or => ["plot/logical_or/#{cc}"]
  plot("plot/logical_or/#{cc}" => datasets[/.*/])
end


dataset(1..1000, /dataset\/logical_or\/(?<compiler>.+)\/(?<impl>.+)/ => [
  'logical_or/main.cpp', proc { |_, match| "logical_or/#{match[:impl]}.rb" }
]) do |n, match|
  require_relative "#{match[:impl]}.rb"
  sequences = [(n-1).times.map { 'false_' } << 'true_']
  binding
end